# Generated by Django 2.1 on 2018-08-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('introduction', models.TextField(max_length=5000)),
                ('time_to_market', models.DateTimeField(verbose_name='time_to_market')),
                ('legal_person', models.CharField(max_length=32)),
                ('assets', models.IntegerField()),
                ('business_property', models.CharField(max_length=32)),
                ('scale', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='company_industry_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.company')),
            ],
        ),
        migrations.CreateModel(
            name='company_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(verbose_name='user established')),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=32)),
                ('field_info', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='finance_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('apartment', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(verbose_name='user established')),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='goverment_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('apartment', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(verbose_name='user established')),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('introduction', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='jadministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(verbose_name='user established')),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='company_user',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.field'),
        ),
        migrations.AddField(
            model_name='company_user',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.industry'),
        ),
        migrations.AddField(
            model_name='company_industry_relationship',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.industry'),
        ),
    ]
