# Generated by Django 2.0.7 on 2018-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='field_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='company_user',
            name='industry_id',
            field=models.CharField(max_length=16),
        ),
    ]
