# Generated by Django 2.0.7 on 2018-08-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20180822_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_user',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='company_user',
            old_name='industry',
            new_name='industry_id',
        ),
    ]
