# Generated by Django 2.0.7 on 2018-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20180822_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_industry_relationship',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='company_industry_relationship',
            name='industry_id',
        ),
        migrations.AddField(
            model_name='company_industry_relationship',
            name='company_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company_industry_relationship',
            name='industry_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
